[project]
name = "garibaldi"
version = "0.10.1"
description = "Victoria 3 Save Games Analyzer"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
]
